complaints/urls.py
from django.urls import path
from . import views
from .models import MedicalIssue, Complaint
from .forms import ComplaintCreationForm, MedicalIssueUpdationForm, ComplaintUpdationForm

app_name= 'complaints'

urlpatterns = [
    path('complaint/new/', views.ComplaintCreateView.as_view(model = Complaint, form_class = ComplaintCreationForm), name='registerComplaint'),
    path('complaint/<int:pk>/', views.ComplaintDetailView.as_view(model = Complaint), name='complaint_detail'),
    path('complaint/<int:pk>/edit', views.ComplaintUpdateView.as_view(model = Complaint, form_class = ComplaintUpdationForm), name='complaint_edit'),
    path('complaint/<int:pk>/delete', views.ComplaintDeleteView.as_view(model = Complaint), name='complaint_delete'),
    path('medical/new/', views.ComplaintCreateView.as_view(model = MedicalIssue, fields = ['summary', 'detailed']), name='registerMedical'),
    path('medical/<int:pk>/', views.ComplaintDetailView.as_view(model = MedicalIssue), name='medicalissue_detail'),
    path('medical/<int:pk>/edit', views.ComplaintUpdateView.as_view(model = MedicalIssue, form_class = MedicalIssueUpdationForm), name='medicalissue_edit'),
    path('medical/<int:pk>/delete', views.ComplaintDeleteView.as_view(model = MedicalIssue), name='medicalissue_delete'),
]

django_auth/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name= 'django_auth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate-email/', ActivationEmailResendView.as_view(), name='send_activate_email'),
    path('activate/<uidb64>/<token>/', account_activate, name='account_activate'),
    path('activation-email-sent/', ActivationEmailSentView.as_view(), name='account_activation_sent'),
    path('change-password/', PasswordChangeView.as_view(), name='change_password'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password-sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]

hosteldb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('institute.urls')),
    path('official/', include('officials.urls')),
    path('student/', include('students.urls')),
    path('', include('complaints.urls')),
    path('staff/', include('workers.urls')),
    
    path('auth/', include('django_auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from . import views

app_name= 'students'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('outings', views.OutingListView.as_view(), name='outing_list'),
    path('outing/new', views.OutingCreateView.as_view(), name='outing_new'),
    path('outing/<int:pk>/edit', views.OutingUpdateView.as_view(), name='outing_edit'),
    path('attendance_history', views.attendance_history, name='attendance_history'),
]

workers/urls.py
from django.urls import path
from . import views

app_name= 'workers'

urlpatterns = [
    path('home/', views.home, name='home'),
]

students/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from institute.constants import FLOOR_OPTIONS

# Create your models here.
class RoomDetail(models.Model):
    student = models.OneToOneField('institute.Student', on_delete=models.CASCADE, null=False)
    block = models.ForeignKey('institute.Block', on_delete=models.SET_NULL, null=True, blank=True)
    room_no = models.IntegerField(null=True, blank=True)
    floor = models.CharField(max_length=10, choices=list(map(lambda floor: (floor, floor), FLOOR_OPTIONS)), null=True, blank=True)

    def __str__(self):
        if self.floor and self.room_no:
            block = self.block_id
            if self.floor == 'Fourth':
                floor = self.floor[:2]
            else:
                floor = self.floor[0]
            return "{regd_no}<{block}: {floor}-{room}>".format(
                regd_no = self.student, 
                block = block,
                floor = floor,
                room = self.room_no
            )
        else:
            return "{}-".format(self.student)

    def clean(self):
        if self.block.roomdetail_set.exclude(pk=self.pk).filter(room_no=self.room_no, floor=self.floor).count() >= self.block.per_room_capacity():
            raise ValidationError("Room filled to maximum capacity.")
        
        if self.floor not in self.block.available_floors():
            raise ValidationError("Floor not available.")

        student = self.student
        block = self.block
        def valid_gender(student, block):
            return student.gender == block.gender
        
        def valid_year(student, block):
            return  ((student.year == 1 and block.room_type == '4S') or \
                    ((student.year == 2 or student.year == 3) and block.room_type == '2S') or \
                    (student.year == 4 and block.room_type == '1S'))

        if block and not valid_gender(student, block):
            raise ValidationError("{} Student cannot be placed in {} block!".format(student.gender, block.gender))
        if block and not valid_year(student, block):
            raise ValidationError("Year: {} Student cannot be placed in {} block!".format(student.year, block.room_type))
    
    def room(self):
        if self.floor and self.room_no:
            if self.floor == 'Fourth':
                floor = self.floor[:2]
            else:
                floor = self.floor[0]
            return "{}-{}".format(floor, self.room_no)
        else:
            return "-"

class Attendance(models.Model):
    OPTIONS = (
        ('Present','Present'),
        ('Absent','Absent')
    )
    student = models.OneToOneField('institute.Student', on_delete=models.CASCADE, null=False)
    present_dates = models.TextField(null=True, blank=True)
    absent_dates = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return str(self.student)

    def mark_attendance(self, date, status):
        if status == 'present':
            absent_dates = self.absent_dates and set(self.absent_dates.split(',')) or set()
            absent_dates.discard(date)
            self.absent_dates = ','.join(absent_dates)
            if not self.present_dates: 
                self.present_dates = date
            else:
                self.present_dates = ','.join(set(self.present_dates.split(',') + [date]))
        elif status == 'absent':
            present_dates = self.present_dates and set(self.present_dates.split(',')) or set()
            present_dates.discard(date)
            self.present_dates = ','.join(present_dates)
            if not self.absent_dates: 
                self.absent_dates = date
            else:
                self.absent_dates = ','.join(set(self.absent_dates.split(',') + [date]))
        if timezone.now().date() == timezone.datetime.strptime(date, "%Y-%m-%d").date():
                self.status = status.title()

        self.save()
        
class Outing(models.Model):
    PERMIT_OPTIONS = (
        ('Pending','Pending'),
        ('Granted', 'Granted'),
        ('Rejected', 'Rejected')
    )

    student = models.ForeignKey('institute.Student', on_delete=models.CASCADE, null=False)
    fromDate = models.DateTimeField(null=False)
    toDate = models.DateTimeField(null=False)
    purpose = models.CharField(max_length=150, null=False)
    permission = models.CharField(max_length=20, choices=PERMIT_OPTIONS, default='Pending', null=False)

    def is_upcoming(self):
        return self.fromDate > timezone.now()

    def is_editable(self):
        return self.is_upcoming() and self.permission == 'Pending'

    class Meta:
        ordering = ['-fromDate']

class Document(models.Model):
    student = models.OneToOneField('institute.Student', on_delete=models.CASCADE, null=False)
    application = models.FileField(null=True, blank=True)
    undertaking_form = models.FileField(null=True, blank=True)
    receipt = models.FileField(null=True, blank=True)
    day_scholar_affidavit = models.FileField(null=True, blank=True)
    aadhar_card = models.FileField(null=True, blank=True)

    def __str__(self) -> str:
        return 'Document: {} - {}'.format(self.id, self.student.regd_no)

class FeeDetail(models.Model):
    student = models.OneToOneField('institute.Student', on_delete=models.CASCADE, null=False)
    has_paid = models.BooleanField(null=True, default=False)
    amount_paid = models.FloatField(null=True, blank=True,default=0)
    bank = models.CharField(max_length=100,null=True, blank=True)
    challan_no = models.CharField(max_length=64,null=True, blank=True)
    dop = models.DateField(null=True, blank=True)

    def __str__(self) -> str:
        return 'Bank Detail: {} - {}'.format(self.id, self.student.regd_no)

students/forms.py
from django import forms
from django.utils import timezone
from .models import Outing

class OutingForm(forms.ModelForm):
    class Meta:
        model = Outing
        fields = ['fromDate', 'toDate', 'purpose']

        labels = {
            'fromDate': 'From Date & Time',
            'toDate': 'To Date & Time'
        }

    def clean(self):
        cleaned_data = super().clean()
        from_date = cleaned_data.get('fromDate')
        to_date = cleaned_data.get('toDate')

        if from_date and to_date and (from_date >= to_date):
            raise forms.ValidationError("To Date and Time should be later than From Date and Time")

        return cleaned_data

    def clean_fromDate(self):
        from_date = self.cleaned_data.get('fromDate')
        if from_date <= timezone.now():
            raise forms.ValidationError("From Date should be later than the moment!")
        return from_date

students/views.py
from django.shortcuts import render
from django.http import Http404
from institute.models import Student
from students.models import Outing
from complaints.models import Complaint
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import CreateView, UpdateView, ListView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy
from .forms import OutingForm


class StudentTestMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_student

def student_check(user):
    return user.is_authenticated and user.is_student

# Create your views here.

@user_passes_test(student_check)
def home(request):
    user = request.user
    student = user.student
    present_dates_count = (student.attendance.present_dates and len(student.attendance.present_dates.split(','))) or 0
    absent_dates_count = (student.attendance.absent_dates and len(student.attendance.absent_dates.split(','))) or 0
    outing_count = len(student.outing_set.all())
    complaints = Complaint.objects.filter(user = user, status="Registered") | Complaint.objects.filter(user = user, status="Processing")

    return render(request, 'students/home.html', {'student': student, 'present_dates_count':present_dates_count, 'absent_dates_count':absent_dates_count, 'outing_count': outing_count, 'complaints':complaints})


class OutingListView(StudentTestMixin, ListView):
    model = Student
    template_name = 'students/outing_list.html'
    context_object_name = 'outing_list'

    def get_queryset(self):
        return self.request.user.student.outing_set.all()


class OutingCreateView(StudentTestMixin, SuccessMessageMixin, CreateView):
    model = Outing
    form_class = OutingForm
    template_name = 'students/outing_form.html'
    success_url = reverse_lazy('students:outing_list')
    success_message = 'Outing application successfully created!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Outing Application'
        return context

    def form_valid(self, form):
        form.instance.student = self.request.user.student
        return super().form_valid(form)

class OutingUpdateView(StudentTestMixin, SuccessMessageMixin, UpdateView):
    model = Outing
    form_class = OutingForm
    template_name = 'students/outing_form.html'
    success_url = reverse_lazy('students:outing_list')
    success_message = 'Outing application successfully updated!'

    def get(self, request, *args, **kwargs):
        response =  super().get(request, *args, **kwargs)
        if not (self.object.student == self.request.user.student and self.object.is_editable()): 
            raise Http404('Cannot edit the outing application.')
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Edit Outing Application'
        return context

    def form_valid(self, form):
        form.instance.student = self.request.user.student
        return super().form_valid(form)


@user_passes_test(student_check)
def attendance_history(request):
    student = request.user.student
    present_dates = (student.attendance.present_dates and student.attendance.present_dates.split(',')) or None
    absent_dates = (student.attendance.absent_dates and student.attendance.absent_dates.split(',')) or None

    return render(request, 'students/attendance_history.html', {'student': student, 'present_dates': present_dates, 'absent_dates': absent_dates})

students/templates/students/attendance_history.html
{% extends 'officials/base_officials.html' %}

{% block title %}Attendance History{% endblock title %}


{% block content %}
<h2 class="text-center">Attendance History</h2>
<hr />

{% include 'students/dates_partial.html' %}
{% endblock content %}

{% block script_links %}
<script>
  var present_dates = [];
  var absent_dates = [];

  {% for date in present_dates %}
    present_dates.push(new Date('{{ date }}'));
  {% endfor %}

  {% for date in absent_dates %}
    absent_dates.push(new Date('{{ date }}'));
  {% endfor %}
</script>
{% load static %}
<script src="{% static 'students/attendance_history.js' %}"></script>
{% endblock script_links %}

students/templates/students/dates_partial.html
{% block style_links %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.9/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.9/dist/plugins/monthSelect/style.css">
{% endblock style_links %}

<div class="text-center">
  <div class="form-group">
    Select Month: 
    <input type="text" id="select_month" class="form-control d-inline w-25 ml-3" />
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-12 col-md-5 border border-success mx-4 p-3 mt-3">
    <h4 class="text-center">Present Dates</h4>
    <div class="row mx-3" id="present_dates_container"></div>
  </div>
  <div class="col-12 col-md-5 border border-danger mx-4 p-3 mt-3">
    <h4 class="text-center">Absent Dates</h4>
    <div class="row mx-3" id="absent_dates_container"></div>
  </div>
</div>

{% block script_links %}
<script>
  var present_dates = [];
  var absent_dates = [];

  {% for date in present_dates %}
    present_dates.push(new Date('{{ date }}'));
  {% endfor %}

  {% for date in absent_dates %}
    absent_dates.push(new Date('{{ date }}'));
  {% endfor %}
</script>

<script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.9/dist/flatpickr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.9/dist/plugins/monthSelect/index.js"></script>
{% load static %}
<script src="{% static 'students/attendance_history.js' %}"></script>

<script>
  flatpickr('#select_month', {
    altInput: true,
    onChange: selectMonth,
    plugins: [
      new monthSelectPlugin({
        shorthand: true, //defaults to false
        altFormat: "F Y", //defaults to "F Y"
        dateFormat: "m-Y", //defaults to "F Y"
      })
    ]
  });
</script>
{% endblock script_links %}

students/templates/students/home.html
{% extends 'officials/base_officials.html' %}

{% block title %}Student Home{% endblock title %}

{% block style_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'officials/home.css' %}">
{% endblock style_links %}

{% block content %}
<h2 class="text-center">Hello {{student.name}}!</h2>

<div class="row mt-4">
  <div class="col-md">
    <div class="card" id="present">
      <div class="row">
        <div class="col-8">
          <span class="row atttext">Number of days present.</span>
          <span class="row attnum">{{ present_dates_count }}</span>
        </div>
        <div class="col-4">
          <span class="atticon"><i class="fa fa-user-plus"></i></span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md">
    <div class="card" id="absent">
      <div class="row">
        <div class="col-8">
          <span class="row atttext">Number of days absent.</span>
          <span class="row attnum">{{ absent_dates_count }}</span>
        </div>
        <div class="col-4">
          <span class="atticon"><i class="fa fa-user-times"></i></span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md">
    <div class="card" id="comps">
      <div class="row">
        <div class="col-8">
          <span class="row atttext">Number of outings.</span>
          <span class="row attnum">{{ outing_count }}</span>
        </div>
        <div class="col-4">
          <span class="atticon"><i class="fa fa-font-awesome"></i></span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row mx-md-4 mt-4 justify-content-center">
  <div class="col-md-4 border p-3">
    <h3 class="text-center border-bottom border-secondary pb-3">Your Details</h3>
    <table class="table table-borderless">
      <tbody id="tbody">
        <tr>
          <th>Name</th>
          <td>{{student.name}}</td>
        </tr>
        <tr>
          <th>Registration No.</th>
          <td>{{student.regd_no}}</td>
        </tr>
        <tr>
          <th>Roll No.</th>
          <td>{{student.roll_no}}</td>
        </tr>
        <tr>
          <th>Year</th>
          <td>{{student.year}}</td>
        </tr>
        <tr>
          <th>Branch</th>
          <td>{{student.branch}}</td>
        </tr>
        <tr>
          <th>Room</th>
          <td>
            {{ student.roomdetail.room }}</td>
        </tr>
        <tr>
          <th>Block</th>
          <td>{{student.roomdetail.block.name}}</td>
        </tr>
        <tr>
          <th>Contact Number</th>
          <td>{{student.phone}}</td>
        </tr>
        <tr>
          <th>e-Mail ID</th>
          <td>{{student.email}}</td>
        </tr>
        <tr>
          <th>Address</th>
          <td>{{student.address}}</td>
        </tr>
      </tbody>
    </table>
    <div class="text-center">
      <a href="{% url 'django_auth:change_password' %}"><button class="btn btn-primary">Change Password</button></a>
    </div>
  </div>
  <div class="col-md-7 border p-3 ml-md-4">
    <h3 class="text-center border-bottom border-secondary pb-3">Complaints Registered</h3>
    <div class="overflow-auto p-3">
      <table class="table table-hover table-muted table-striped" id="complaints_table">
        <thead>
          <tr>
            <th class="text-center">Type</th>
            <th class="text-center">Complainee</th>
            <th class="text-center">Summary</th>
            <th class="text-center">Last Updated</th>
            <th class="text-center">Status</th>
          </tr>
        </thead>
        <tbody>
  
          {% for item in complaints %}
          <tr data-row-href="{% url 'complaints:complaint_detail' item.id %}">
            <td class="text-center">{{item.type}}</td>
            <td class="text-center">{{item.complainee}}</td>
            <td class="text-center">{{item.summary}}</td>
            <td class="text-center">{{item.updated_at|date:'d-m-Y'}}</td>
            <td class="text-center">{{item.status}}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="7" class="text-center"> No complaints registered! </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock content %}


{% block script_links %}

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
  $(document).ready(function () {
    $('#complaints_table').DataTable({
      "pageLength": 6,
      "lengthChange": false,
      "filter": false
    });


  });
</script>

{% endblock script_links %}

students/templates/students/outing_form.html
{% extends 'officials/base_public_forms.html' %}
{% block title %}Outing Application{% endblock title %}


{% block style_links %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock style_links %}
  

{% block content %}

{% load crispy_forms_tags %}
<form method="post">
  {% csrf_token %}
  <div class="card-body text-capitalize">
    <div class="row">
      <div class="col-12">
        {{ form|crispy }}
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row justify-content-center">
      <button type="submit" class="btn btn-warning px-4 py-2">Apply</button>
    </div>
  </div>
</form>
  
{% endblock content %}


{% block script_links %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script>
  flatpickr('#id_fromDate', {
    altInput: true,
    altFormat: "M j, Y H:i",
    enableTime: true,
    minDate: "today",
    time_24hr: true
  });
  flatpickr('#id_toDate', {
    altInput: true,
    altFormat: "M j, Y H:i",
    enableTime: true,
    minDate: "today",
    time_24hr: true
  });

</script>
{% endblock script_links %}
  

students/templates/students/outing_list.html
{% extends 'officials/base_officials.html' %}

{% block title %}Outing History{% endblock title %}


{% block content %}
<h2 class="text-center">Outing History</h2>
<hr />

<h4 class="ml-4">Upcoming Outings</h4>
<div class="overflow-auto p-3">
  <table class="table table-hover table-muted table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>From</th>
        <th>To</th>
        <th>Purpose of Visit</th>
        <th>Permission</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for outing in outing_list %}
        {% if outing.is_upcoming %}
          <tr>
            <td>{{ outing.id }}</td>
            <td nowrap>{{ outing.fromDate }}</td>
            <td nowrap>{{ outing.toDate }}</td>
            <td>{{ outing.purpose }}</td>
            <td
              {% if outing.permission == 'Pending' %}
                class="text-primary"
              {% endif %}
              {% if outing.permission == 'Granted' %}
                class="text-success"
              {% endif %}
              {% if outing.permission == 'Rejected' %}
                class="text-danger"
              {% endif %}
            >
              {{ outing.permission }}
            </td>
            <td nowrap>
              {% if outing.is_editable %}
                <a href="{% url 'students:outing_edit' outing.id %}" target="_blank" class="btn btn-primary">Edit</a>
              {% endif %}
            </td>
          </tr>
        {% endif %}
      {% endfor %}
    </tbody>
  </table>
</div>

<h4 class="ml-4">Past Outings</h4>
<div class="overflow-auto p-3">
  <table class="table table-hover table-muted table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>From</th>
        <th>To</th>
        <th>Purpose of Visit</th>
        <th>Permission</th>
      </tr>
    </thead>
    <tbody>
      {% for outing in outing_list %}
        {% if not outing.is_upcoming %}
          <tr>
            <td>{{ outing.id }}</td>
            <td nowrap>{{ outing.fromDate }}</td>
            <td nowrap>{{ outing.toDate }}</td>
            <td>{{ outing.purpose }}</td>
            <td
              {% if outing.permission == 'Pending' %}
                class="text-primary"
              {% endif %}
              {% if outing.permission == 'Granted' %}
                class="text-success"
              {% endif %}
              {% if outing.permission == 'Rejected' %}
                class="text-danger"
              {% endif %}
            >
              {{ outing.permission }}
            </td>
          </tr>
        {% endif %}
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}