django_auth/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name= 'django_auth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate-email/', ActivationEmailResendView.as_view(), name='send_activate_email'),
    path('activate/<uidb64>/<token>/', account_activate, name='account_activate'),
    path('activation-email-sent/', ActivationEmailSentView.as_view(), name='account_activation_sent'),
    path('change-password/', PasswordChangeView.as_view(), name='change_password'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password-sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]

hosteldb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('institute.urls')),
    path('official/', include('officials.urls')),
    path('student/', include('students.urls')),
    path('', include('complaints.urls')),
    path('staff/', include('workers.urls')),
    
    path('auth/', include('django_auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

institute/urls.py
from django.urls import path

from . import views

app_name= 'institute'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery',views.gallery, name='gallery'),
    path('block-gallery/',views.hostels,name='hostels'),
    path('contact/',views.contact,name='contact'),
    path('developer-team/',views.developers, name='developers'),

]

workers/urls.py
from django.urls import path
from . import views

app_name= 'workers'

urlpatterns = [
    path('home/', views.home, name='home'),
]

django_auth/models.py
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from .tokens import account_activation_token
from django.core.mail import EmailMultiAlternatives

class UserManager(BaseUserManager):
    def create_user(self, email, type_flag, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email))
        if type_flag == 'student':
            user.is_student = True
        elif type_flag == 'official':
            user.is_official = True
        elif type_flag == 'worker':
            user.is_worker = True
        else:
            raise ValueError('User type should be one of the following:\n student, official, worker')

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        
        user = self.create_user(email=email, password=password, type_flag='official')
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=250,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    is_student = models.BooleanField(default=False)
    is_official = models.BooleanField(default=False)
    is_worker = models.BooleanField(default=False)

    email_confirmed = models.BooleanField(default=True)

    #Add eMail here when both username(id) and eMail required
    # REQUIRED_FIELDS = ['email', ]

    objects = UserManager()

    def __str__(self):
        return self.email

    USERNAME_FIELD = 'email'

    def entity(self):
        return (self.is_student and self.student) or \
            (self.is_official and self.official) or \
            (self.is_worker and self.worker)
    
    def entity_id(self):
        return (self.is_student and self.student.regd_no) or \
            (self.is_official and self.official.emp_id) or \
            (self.is_worker and self.worker.staff_id)

    def entity_type(self):
        return (self.is_student and 'Student') or \
            (self.is_official and 'Official') or \
            (self.is_worker and 'Worker')

    def home_url(self):
        if self.is_student:
            return reverse('students:home')
        elif self.is_official:
            return reverse('officials:home')
        elif self.is_worker:
            return reverse('workers:home')

    def send_activation_email(self, request, from_email=None, **kwargs):
        current_site = get_current_site(request)
        subject = 'Activate your Hostel Management System Account.'
        email_context = {
            'user': self,
            'protocol': request.scheme,
            'domain': request.get_host(),
            'uid': urlsafe_base64_encode(force_bytes(self.pk)),
            'token': account_activation_token.make_token(self),
        }
        email_template = 'django_auth/account_activation_email_text.html'
        html_email_template = 'django_auth/account_activation_email_html.html'
        
        self.email_user(subject, email_context, email_template, html_email_template)


    def email_user(self, subject, context, email_template, html_email_template, from_email=None, **kwargs):
        body = render_to_string(email_template, context)
        email_message = EmailMultiAlternatives(subject, body, from_email, [self.email])
        html_email = render_to_string(html_email_template, context)
        email_message.attach_alternative(html_email, 'text/html')
        email_message.send()

django_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from institute.models import Student, Official
from workers.models import Worker
from django.utils.safestring import mark_safe
from django.urls import reverse_lazy

class LoginForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.email_confirmed:
            raise forms.ValidationError(
                mark_safe('Please verify your email to activate your account. <a href="{}">Click to resend the activation link.</a>'.format(reverse_lazy('django_auth:send_activate_email'))),
                code='email_unverified',
            )

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'is_student', 'is_official', 'is_worker')
        
        help_texts = {
            'username': None,
            'password1': None,
            'password2': None,
        }
        labels = {
            'is_student': 'Student',
            'is_official': 'Official',
            'is_worker': 'Staff'
        }

    def clean(self):
        cleaned_data = super().clean()
        is_student = cleaned_data.get('is_student')
        is_official = cleaned_data.get('is_official')
        is_worker = cleaned_data.get('is_worker')
        email = cleaned_data.get('email')

        if not(is_student or is_official or is_worker):
            raise forms.ValidationError('User should belong to a single type.')

        if (is_student and is_official) or (is_student and is_worker) or (is_worker and is_official):
            raise forms.ValidationError('User cannot be of more than one type.')

        if email and is_student and (not email.endswith('@student.nitandhra.ac.in')):
            raise forms.ValidationError('Students should use institute eMail ID')

        if email and (is_worker or is_official) and (not email.endswith('@nitandhra.ac.in')):
            raise forms.ValidationError('Staff should use institute eMail ID')

        if not ((is_student and Student.objects.filter(account_email = email).exists()) or (is_official and Official.objects.filter(account_email = email).exists()) or  (is_worker and Worker.objects.filter(account_email = email).exists())):
            if is_student:
                user_type = 'Student'
            elif is_official or is_worker:
                user_type = 'Staff'

            raise forms.ValidationError(user_type + " doesn't exist in database. Please contact admin.")
                
        return cleaned_data


class ActivationEmailForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

django_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView, FormView
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from .models import User
from .forms import SignUpForm, LoginForm, ActivationEmailForm
from institute.models import Student, Official
from workers.models import Worker
from django.contrib.auth import login, get_user_model
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from .tokens import account_activation_token

User = get_user_model()

# Create your views here.

class LoginView(SuccessMessageMixin, auth_views.LoginView):
    template_name='django_auth/login.html'
    form_class = LoginForm

    def get_success_url(self):
        return self.request.user.home_url()

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['form_title'] = 'Log In'
        return context

class SignUpView(CreateView):
    template_name = 'django_auth/signup.html'
    form_class = SignUpForm

    def get_success_url(self):
        return reverse('django_auth:account_activation_sent')

    def form_valid(self, form):
        form.instance.email_confirmed = False

        response = super().form_valid(form)
        
        # After save, send confirmation email
        user = form.instance
        user.send_activation_email(self.request)
        
        # After save assign to entity!
        is_student = form.cleaned_data.get('is_student')
        is_official = form.cleaned_data.get('is_official')
        is_worker = form.cleaned_data.get('is_worker')
        email = form.cleaned_data.get('email')

        if is_student:
            Student.objects.filter(account_email = email).update(user = user)
        elif is_official:
            Official.objects.filter(account_email = email).update(user = user)
        elif is_worker:
            Worker.objects.filter(account_email = email).update(user = user)
        return response
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['form_title'] = 'Sign Up'
        return context

def account_activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.email_confirmed = True
        user.save()
        messages.success(request, 'Account email verified!')
        login(request, user)
        return redirect(user.home_url())
    else:
        return render(request, 'django_auth/account_activation_invalid.html', {'form_title': 'Account Activation Failed'})

class ActivationEmailResendView(FormView):
    template_name = 'django_auth/password_change.html'
    form_class = ActivationEmailForm
    success_url = reverse_lazy('django_auth:account_activation_sent')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        users = User.objects.filter(email = email, is_active = True, email_confirmed = False)
        for user in users:
            user.send_activation_email(self.request)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Send Account Activation Email'
        return context

class ActivationEmailSentView(TemplateView):
    template_name = 'django_auth/account_activation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Account Activation Email sent'
        return context

class PasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, auth_views.PasswordChangeView):
    template_name = 'django_auth/password_change.html'

    def get_success_url(self):
        return self.request.user.home_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Change Password'
        return context


class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'django_auth/password_change.html'
    subject_template_name = 'django_auth/password_reset_subject.txt'
    email_template_name = 'django_auth/password_reset_email_text.html'
    html_email_template_name = 'django_auth/password_reset_email_html.html'
    success_url = reverse_lazy('django_auth:password_reset_done')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Reset Password'
        return context

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'django_auth/password_reset_done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Reset Password eMail Sent'
        return context

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'django_auth/password_reset_confirm.html'
    success_url = reverse_lazy('django_auth:password_reset_complete')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Reset New Password'
        return context

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'django_auth/password_reset_complete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Password Reset Complete'
        return context

django_auth/templates/django_auth/account_activation_email_html.html
{% extends 'django_auth/mail_template.html' %}

{% block title %}Activate Account{% endblock title %}

{% block content %}
<p>Tap the button below to verify your email and activate your account. </p>
<a href="{{ protocol }}://{{ domain }}{% url 'django_auth:account_activate' uidb64=uid token=token %}" target="_blank" class="btn">Reset Password</a>
<p>If that doesn't work, copy and paste the following link in your browser:</p>
<p><a href="{{ protocol }}://{{ domain }}{% url 'django_auth:account_activate' uidb64=uid token=token %}" target="_blank">{{ protocol }}://{{ domain }}{% url 'django_auth:account_activate' uidb64=uid token=token %}</a></p>
{% endblock content %}
                

{% block footer %}
If you do not recognize this activity, kindly contact us at <a href="mailto:chiefwarden@nitandhra.ac.in">chiefwarden@nitandhra.ac.in</a>
{% endblock footer %}

django_auth/templates/django_auth/account_activation_email_text.html
Activate Account - Hostel Management System, NIT Andhra Pradesh

Please open the following link to verify your email and activate your account:
{{ protocol }}://{{ domain }}{% url 'django_auth:account_activate' uidb64=uid token=token %}

Cheers,
Team Hostel Management System,
National Institute of Technology, Andhra Pradesh.

django_auth/templates/django_auth/account_activation_invalid.html
{% extends 'officials/base_public_forms.html' %}
{% block title %}{{ form_title }}{% endblock title %}

{% block content %}
<div class="card-body text-center">
	Uh oh! Seems like you followed the wrong link. <span class="text-primary">Please verify the link from your inbox!</span>
</div>
<div class="card-footer text-center p-4">
	<a href="{% url 'django_auth:login' %}" class="btn btn-warning px-4 py-2">Login</a>
</div>
{% endblock content %}

django_auth/templates/django_auth/account_activation_sent.html
{% extends 'officials/base_public_forms.html' %}
{% block title %}{{ form_title }}{% endblock title %}

{% block content %}
<div class="card-body text-center">
	We've sent you an eMail with a link to activate your account. <br><span class="text-danger">Please check your eMail inbox.</span>
</div>
<div class="card-footer text-center p-4">
	<a href="{% url 'django_auth:login' %}" class="btn btn-warning px-4 py-2">Login</a>
</div>
{% endblock content %}

django_auth/templates/django_auth/login.html
{% extends 'officials/base_public_forms.html' %}
{% block title %}{{ form_title }}{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<form method="post">
	<div class="card-body">
		{% csrf_token %}
		
		{{ form|crispy }}
		<div class="row justify-content-center">
			<button type="submit" class="btn btn-warning px-4 py-2">Log in</button>
		</div>
	</div>
</form>
<div class="card-footer">
	<div class="row mt-2 d-flex justify-content-center">
		<a href="{% url 'django_auth:signup' %}">Sign Up</a>
	</div>
	<div class="row d-flex justify-content-center">
		<a href="{% url 'django_auth:password_reset' %}">Forgot Password?</a>
	</div>
	<div class="row d-flex justify-content-center">
		<a href="{% url 'institute:index' %}">Home</a>
	</div>
</div>
{% endblock content %}

django_auth/templates/django_auth/password_reset_complete.html
{% extends 'officials/base_public_forms.html' %}
{% block title %}{{ form_title }} {% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<div class="card-body text-center">
	We've set up your account with the new password. Please go ahead and log in.
</div>
<div class="card-footer text-center p-4">
	<a href="{% url 'django_auth:login' %}" class="btn btn-warning px-4 py-2">Login</a>
</div>
{% endblock content %}

django_auth/templates/django_auth/password_reset_done.html
{% extends 'officials/base_public_forms.html' %}
{% block title %}{{ form_title }} {% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<div class="card-body text-center">
	We've sent you an eMail with a link to reset your password and further instructions. <br><span class="text-danger">Please check your eMail inbox.</span>
</div>
<div class="card-footer text-center p-4">
	<a href="{% url 'django_auth:login' %}" class="btn btn-warning px-4 py-2">Login</a>
</div>
{% endblock content %}

django_auth/templates/django_auth/password_reset_email.html
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Password Reset</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style type="text/css">
  /**
   * Google webfonts. Recommended to include the .woff version for cross-client compatibility.
   */
  @media screen {
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 400;
      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
    }

    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 700;
      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');
    }
  }

  /**
   * Avoid browser level font resizing.
   * 1. Windows Mobile
   * 2. iOS / OSX
   */
  body,
  table,
  td,
  a {
    -ms-text-size-adjust: 100%; /* 1 */
    -webkit-text-size-adjust: 100%; /* 2 */
  }

  /**
   * Remove extra space added to tables and cells in Outlook.
   */
  table,
  td {
    mso-table-rspace: 0pt;
    mso-table-lspace: 0pt;
  }

  /**
   * Better fluid images in Internet Explorer.
   */
  img {
    -ms-interpolation-mode: bicubic;
  }

  /**
   * Remove blue links for iOS devices.
   */
  a[x-apple-data-detectors] {
    font-family: inherit !important;
    font-size: inherit !important;
    font-weight: inherit !important;
    line-height: inherit !important;
    color: inherit !important;
    text-decoration: none !important;
  }

  /**
   * Fix centering issues in Android 4.4.
   */
  div[style*="margin: 16px 0;"] {
    margin: 0 !important;
  }

  body {
    width: 100% !important;
    height: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
  }

  /**
   * Collapse table borders to avoid space between cells.
   */
  table {
    border-collapse: collapse !important;
  }

  a {
    color: #1a82e2;
  }

  img {
    height: auto;
    line-height: 100%;
    text-decoration: none;
    border: 0;
    outline: none;
  }
  </style>

</head>
<body style="background-color: #e9ecef;">
	{% load static %}
  <!-- start preheader -->
  <div class="preheader" style="display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;">
    We've receiver a request to reset your password.
  </div>
  <!-- end preheader -->

  <!-- start body -->
  <table border="0" cellpadding="0" cellspacing="0" width="100%">

    <!-- start logo -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="center" valign="top" style="padding: 36px 24px;">
              <a href="https://www.nitandhra.ac.in/main/" target="_blank" style="display: inline-block;">
                <img src="{% static 'officials/logo_small.png' %}" alt="Logo" border="0" width="48" style="display: block; width: 48px; max-width: 48px; min-width: 48px;">
              </a>
            </td>
          </tr>
        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
    <!-- end logo -->

    <!-- start hero -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #d4dadf;">
              <h1 style="margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;">Reset Your Password</h1>
            </td>
          </tr>
        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
    <!-- end hero -->

    <!-- start copy block -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

          <!-- start copy -->
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
              <p style="margin: 0;">Tap the button below to reset your account password. If you didn't request a new password, you can safely ignore or delete this email.</p>
            </td>
          </tr>
          <!-- end copy -->

          <!-- start button -->
          <tr>
            <td align="left" bgcolor="#ffffff">
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td align="center" bgcolor="#ffffff" style="padding: 12px;">
                    <table border="0" cellpadding="0" cellspacing="0">
                      <tr>
                        <td align="center" bgcolor="#1a82e2" style="border-radius: 6px;">
                          <a href="{{ protocol }}://{{ domain }}{% url 'django_auth:password_reset_confirm' uidb64=uid token=token %}" target="_blank" style="display: inline-block; padding: 16px 36px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; color: #ffffff; text-decoration: none; border-radius: 6px;">Do Something Sweet</a>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- end button -->

          <!-- start copy -->
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
              <p style="margin: 0;">If that doesn't work, copy and paste the following link in your browser:</p>
              <p style="margin: 0;"><a href="{{ protocol }}://{{ domain }}{% url 'django_auth:password_reset_confirm' uidb64=uid token=token %}" target="_blank">{{ protocol }}://{{ domain }}{% url 'django_auth:password_reset_confirm' uidb64=uid token=token %}</a></p>
            </td>
          </tr>
          <!-- end copy -->

          <!-- start copy -->
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border-bottom: 3px solid #d4dadf">
              <p style="margin: 0;">Cheers,<br> <a href="https://www.linkedin.com/in/eswar-clynn" style="text-decoration: none;">Team Hostel Management System,<br>National Institute of Technology, Andhra Pradesh</a> </p>
            </td>
          </tr>
          <!-- end copy -->

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
    <!-- end copy block -->

    <!-- start footer -->
    <tr>
      <td align="center" bgcolor="#e9ecef" style="padding: 24px;">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

          <!-- start permission -->
          <tr>
            <td align="center" bgcolor="#e9ecef" style="padding: 12px 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">
              <p style="margin: 0;">You received this email because we received a request for reset password for your account. If you didn't request reset password you can safely ignore or delete this email.</p>
            </td>
          </tr>
          <!-- end permission -->

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
    <!-- end footer -->

  </table>
  <!-- end body -->

</body>
</html>

django_auth/templates/django_auth/signup.html
{% extends 'officials/base_public_forms.html' %}
{% block title %}{{ form_title }} {% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<div class="card-body">
     <form method="post">{% csrf_token %}
          {{ form|as_crispy_errors }}
          {{form.email|as_crispy_field}}
          {{form.password1|as_crispy_field}}
          {{form.password2|as_crispy_field}}
          <div class="row justify-content-center text-center">
               <div class="col-12 col-md-3">{{form.is_student|as_crispy_field}} </div>
               <div class="col-12 col-md-3">{{form.is_official|as_crispy_field}} </div>
               <div class="col-12 col-md-3">{{form.is_worker|as_crispy_field}} </div>
          </div>
          <div class="row justify-content-center">
               <button type="submit" class="btn btn-warning px-4 py-2">Sign Up</button>
          </div>
     </form>
</div>
<div class="card-footer py-3">
     <div class="row d-flex justify-content-center">
          <a href="{% url 'django_auth:login' %}">Login</a>
     </div>
	<div class="row d-flex justify-content-center">
		<a href="{% url 'institute:index' %}">Home</a>
	</div>   
</div>
{% endblock content %}

{% block script_links %}
<script>
     var s = document.getElementById('id_is_student');
     var o = document.getElementById('id_is_official');
     var w = document.getElementById('id_is_worker');

     s.onclick =  () => {
          o.checked = false;
          w.checked = false;
     }
     w.onclick = () => {
          s.checked = false;
          o.checked = false;
     }
     o.onclick = () => {
          s.checked = false;
          w.checked = false;
     }

</script>
{% endblock script_links %}