django_auth/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name= 'django_auth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate-email/', ActivationEmailResendView.as_view(), name='send_activate_email'),
    path('activate/<uidb64>/<token>/', account_activate, name='account_activate'),
    path('activation-email-sent/', ActivationEmailSentView.as_view(), name='account_activation_sent'),
    path('change-password/', PasswordChangeView.as_view(), name='change_password'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password-sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]

hosteldb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('institute.urls')),
    path('official/', include('officials.urls')),
    path('student/', include('students.urls')),
    path('', include('complaints.urls')),
    path('staff/', include('workers.urls')),
    
    path('auth/', include('django_auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

institute/urls.py
from django.urls import path

from . import views

app_name= 'institute'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery',views.gallery, name='gallery'),
    path('block-gallery/',views.hostels,name='hostels'),
    path('contact/',views.contact,name='contact'),
    path('developer-team/',views.developers, name='developers'),

]

workers/urls.py
from django.urls import path
from . import views

app_name= 'workers'

urlpatterns = [
    path('home/', views.home, name='home'),
]

institute/models.py
import complaints
from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings
from django.core.validators import MinLengthValidator
from institute.validators import numeric_only, date_no_future
from institute.constants import FLOOR_OPTIONS

# Create your models here.
class Student(models.Model):
    YEAR = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
    )

    GENDER=(
        ('Male','Male'),
        ('Female','Female'),
    )

    def photo_storage_path(instance, filename):
        extension = filename.split('.')[-1]
        return 'Student-Photos/Year-{}/{}.{}'.format(instance.year, instance.regd_no, extension)

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    account_email = models.EmailField(unique=True, null=False)
    regd_no = models.CharField(unique=True, null=False, max_length=6, validators=[MinLengthValidator(6)])
    roll_no = models.CharField(unique=True, null=False, max_length=6, validators=[MinLengthValidator(6)])
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(null=True, blank=True)
    year = models.IntegerField(null=False, choices=YEAR)
    branch = models.CharField(max_length=40,null=False)
    gender = models.CharField(max_length=7,choices=GENDER,null=False)
    pwd = models.BooleanField(null=False, default=False)
    community = models.CharField(max_length=25, null=True, blank=True)
    aadhar_number = models.CharField(max_length=15, null=True, blank=True)
    dob = models.DateField(null=False, validators=[date_no_future])
    blood_group = models.CharField(max_length=25, null=True, blank=True)
    father_name = models.CharField(max_length=100, null=True, blank=True)
    mother_name = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(null=False, max_length=10, validators=[numeric_only])
    parents_phone = models.CharField(null=False, max_length=10, validators=[numeric_only])
    emergency_phone = models.CharField(null=True, blank=True, max_length=10, validators=[numeric_only])
    address = models.TextField(null=False)
    photo = models.ImageField(null=True, blank=True, upload_to=photo_storage_path)
    is_hosteller = models.BooleanField(null=False, default=True)

    def __str__(self):
        return str(self.regd_no)

    def clean(self):
        super().clean()
        if not self.is_hosteller and hasattr(self, 'roomdetail'):
            raise ValidationError("Day scholars cannot be alloted a room.")

    def block(self):
        return self.roomdetail.block


class Official(models.Model):
    EMP=(
        ('Caretaker','Caretaker'),
        ('Warden','Warden'),
        ('Deputy Chief-Warden', 'Deputy Chief-Warden'),
        ('Chief-Warden','Chief-Warden'),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    account_email = models.EmailField(unique=True, null=False)
    emp_id = models.CharField(unique=True,null=False, max_length=20)
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=20,choices=EMP)
    phone = models.CharField(max_length=10, null=False, validators=[numeric_only])
    email = models.EmailField(null=True, blank=True)
    block = models.ForeignKey('institute.Block', on_delete=models.SET_NULL, null=True, blank=True)

    def is_chief(self):
        return (self.designation == 'Deputy Chief-Warden' or self.designation == 'Chief-Warden')

    def clean(self):
        if self.is_chief() and self.block != None:
            raise ValidationError('Chief Warden and Deputy Chief Warden cannot be assigned a block.')

    def related_complaints(self, pending=True):
        if self.is_chief():
            if pending:
                return complaints.models.Complaint.objects.filter(status__in=['Registered', 'Processing']) # | complaints.models.Complaint.objects.filter(status='Processing')
            else:
                return complaints.models.Complaint.objects.all()
        else:
            students = self.block.students()
            users = students.values_list('user', flat=True)
            if pending:
                return complaints.models.Complaint.objects.filter(user__in=users, status__in=['Registered', 'Processing']) | self.user.complaint_set.filter(status__in=['Registered', 'Processing'])
            else:
                return complaints.models.Complaint.objects.filter(user__in=users) | self.user.complaint_set.all()

    def related_medical_issues(self, pending=True):
        if self.is_chief():
            if pending:
                return complaints.models.MedicalIssue.objects.filter(status='Registered')
            else:
                return complaints.models.MedicalIssue.objects.all()
        else:
            students = self.block.students()
            users = students.values_list('user', flat=True)
            if pending:
                return complaints.models.MedicalIssue.objects.filter(user__in=users, status='Registered') | self.user.medicalissue_set.filter(status='Registered')
            else:
                return complaints.models.MedicalIssue.objects.filter(user__in=users) | self.user.medicalissue_set.all()
                

    def __str__(self):
        return str(self.emp_id)


class Block(models.Model):
    OPTION=(
          ('1S','One student per Room'),
          ('2S','Two students per Room'),
          ('4S','Four students per Room'),
     )

    GENDER=(
        ('Male','Male'),
        ('Female','Female'),
     )

    block_id = models.CharField(unique=True, max_length=20)
    name = models.CharField(max_length=50,null=False)
    room_type = models.CharField(max_length=2,choices=OPTION)
    gender = models.CharField(max_length=7,choices=GENDER)
    floor_count = models.IntegerField(null=False, verbose_name="No. of Floors")
    capacity = models.IntegerField(null=False)

    def __str__(self):
        return self.name

    def short_name(self):
        return self.name.split()[0]

    def available_floors(self):
        return FLOOR_OPTIONS[:self.floor_count]

    def per_room_capacity(self):
        import re
        # Regex to find room_capacity from room_type
        return int(re.search(r'\d+', self.room_type).group())

    def student_capacity(self):
        if self.room_type == '4S':   return self.capacity*4
        elif self.room_type == '2S': return self.capacity*2
        elif self.room_type == '1S': return self.capacity

    def roomdetails(self):
        return self.roomdetail_set.all()

    def students(self):
        student_rooms = self.roomdetail_set.all()
        student_ids = student_rooms.values_list('student', flat=True)
        return Student.objects.filter(pk__in=student_ids)

    def caretaker(self):
        return self.official_set.filter(designation='Caretaker').first()

    def warden(self):
        return self.official_set.filter(designation='Warden').first()

institute/views.py
from django.shortcuts import render
from institute.models import Block

# Create your views here.
def index(request):
    return render(request, 'institute/index.html')

def gallery(request):
    return render(request, 'institute/grid-gallery.html')

def hostels(request):
    blocks = Block.objects.all()
    return render (request,'institute/hostels.html',{'blocks': blocks})

def contact(request):
    return render (request,'institute/contact.html')

def developers(request):
    return render(request,'institute/developers.html')

institute/templates/institute/base_public_pages.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}{% endblock %} - Hostel Management System </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css" integrity="sha512-O03ntXoVqaGUTAeAmvQ2YSzkCvclZEcPQu1eqloPaHfJ5RuNGiS4l+3duaidD801P50J28EHyonCV06CUlTSag==" crossorigin="anonymous" />
  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,500&display=swap"
    rel="stylesheet">
  {% load static %}
  <link href="{% static 'officials/application.css' %}" rel="stylesheet">
  <link href="{% static 'officials/public_pages.css' %}" rel="stylesheet">
  {% block style_links %}{% endblock style_links %}
    
</head>
<body>
  <nav class="navbar fixed-top row px-4" id="topnav">
    <div class="col-12 d-flex justify-content-center">
      <a href="{% url 'institute:index' %}" class="d-none d-md-block nav-title"><img src="{% static 'officials/logo_small.png' %}" alt="Institute Logo" class="mr-3">NIT Andhra Pradesh - Hostel Management System</a>
      <a href="{% url 'institute:index' %}" class="d-block d-md-none nav-title"><img src="{% static 'officials/logo_small.png' %}" alt="Institute Logo" class="mr-2">NIT AP - Hostels</a>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  {% block script_links %}{% endblock script_links %}
  <script src="{% static 'officials/application.js' %}"></script>
</body>
</html>

institute/templates/institute/contact.html
{% extends 'institute/base_public_pages.html' %}

{% block title %}Contact{% endblock title %}

{% block style_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'institute/cards.css' %}">
{% endblock style_links %}


{% block content %}
<div class="container-fluid my-5 pt-5">
  <div class="row justify-content-center mx-md-3 p-3">
    <div class="col-12">
      <div class="row justify-content-between">
        <div class="col-md-2"></div>
        <div class="col-md-8 text-center">
          <h2 class="d-inline border-bottom border-info">Contact Us!</h2>
        </div>
        <div class="col-md-2 text-center text-md-right mt-3 mt-md-0">
          <a href="{% url 'institute:developers' %}" class="btn btn-primary">Dev Team</a>
        </div>
      </div>
    </div>
    <div class="col-12 mt-3">
      <h4 class="text-center">NIT Andhra Pradesh Hostel Committee</h4>
    </div>
    <div class="col-12 col-md-6 col-lg-4 col-xl-2 p-3 d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'institute/DIN.jpg' %}" alt="Block Image"
          style="width: auto; height: 250px;">
        <div class="card-body">
          <h5 class="card-title">Dr. Dinesh P Sankar Reddy</h5>
          <div class="card-text">
            <p >Registrar</p>
          </div>
          <div class="card-reveal">
            <h4>Dr. Dinesh P Sankar Reddy</h4>
            <p >Registrar</p>
            <h5 class="mt-4">Contact:</h5>
            <p>Phone: +91-7975624892</p>
            <p>eMail ID: <a href="mailto:registrar@nitandhra.ac.in">registrar@nitandhra.ac.in</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-4 col-xl-2 p-3 d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'institute/TR.jpg' %}" alt="Block Image"
          style="width: auto; height: 250px;">
        <div class="card-body">
          <h5 class="card-title">Dr. Tejavathu Ramesh</h5>
          <div class="card-text">
            <p >Deputy Registrar (Hostels)</p>
          </div>
          <div class="card-reveal">
            <h4>Dr. Tejavathu Ramesh</h4>
            <p >Deputy Registrar (Hostels)</p>
            <h5 class="mt-4">Contact:</h5>
            <p>Phone: +91-9034003377</p>
            <p>eMail ID: <a href="mailto:dr_hostels@nitandhra.ac.in">dr_hostels@nitandhra.ac.in</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-4 col-xl-2 p-3 d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'institute/JKM.jpg' %}" alt="Block Image"
          style="width: auto; height: 250px;">
        <div class="card-body">
          <h5 class="card-title">Dr. J. Krishnamurthy</h5>
          <div class="card-text">
            <p>Chief Warden</p>
          </div>
          <div class="card-reveal">
            <h4>Dr. J. Krishnamurthy</h4>
            <span>Chief Warden</span>
            <h5 class="mt-4">Contact:</h5>
            <p>Phone: +91-7975624892</p>
            <p>eMail ID: <a href="mailto:chiefwarden@nitandhra.ac.in">chiefwarden@nitandhra.ac.in</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-4 col-xl-2 p-3 d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'institute/srilatha.jpg' %}" alt="Block Image"
          style="width: auto; height: 250px;">
        <div class="card-body">
          <h5 class="card-title">Dr. Srilatha Chebrolu</h5>
          <div class="card-text">
            <p>Deputy Chief Warden-Girls</p>
          </div>
          <div class="card-reveal">
            <h4>Dr. Srilatha Chebrolu</h4>
            <span>Deputy Chief Warden-Girls</span>
            <h5 class="mt-4">Contact:</h5>
            <p>Phone: +91-8330967036</p>
            <p>eMail ID: <a href="mailto:srilatha.chebrolu@nitandhra.ac.in">srilatha.chebrolu@nitandhra.ac.in</a></p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 col-xl-2 p-3 d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'institute/RMD.jpg' %}" alt="Block Image"
          style="width: auto; height: 250px;">
        <div class="card-body">
          <h5 class="card-title">Dr. M. Ramudu</h5>
          <div class="card-text">
            <p>Deputy Chief Warden-Boys</p>
          </div>
          <div class="card-reveal">
            <h4>Dr. Srilatha Chebrolu</h4>
            <span>Deputy Chief Warden-Boys</span>
            <h5 class="mt-4">Contact:</h5>
            <p>Phone: +91-9949142717</p>
            <p>eMail ID: <a href="mailto:ramudu@nitandhra.ac.in">ramudu@nitandhra.ac.in</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row justify-content-center mx-md-3 p-3 mt-4 border-top border-secondary">
    <div class="col-12 mt-3">
      <h4 class="text-center">Hostel Incharges</h4>
    </div>
    <div class="col-12 col-md-6 col-lg-4 col-xl-2 p-3 d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'institute/placeholder.jpg' %}" alt="Block Image"
          style="width: auto; height: 250px;">
        <div class="card-body">
          <h5 class="card-title">Mr. Rakesh Singh</h5>
          <div class="card-text">
            <p>Security Officer</p>
          </div>
          <div class="card-reveal">
            <h4>Mr. Rakesh Singh</h4>
            <span>Security Officer</span>
            <h5 class="mt-4">Contact:</h5>
            <p>Phone: +91 9945636541</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-4 col-xl-2 p-3 d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'institute/placeholder.jpg' %}" alt="Block Image"
          style="width: auto; height: 250px;">
        <div class="card-body">
          <h5 class="card-title">Mr. Raghu Ram</h5>
          <div class="card-text">
            <p>Housekeeping Incharge</p>
          </div>
          <div class="card-reveal">
            <h4>Mr. Raghu Ram</h4>
            <span>Housekeeping Incharge</span>
            <h5 class="mt-4">Contact:</h5>
            <p>Phone: +91 9784263011</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block script_links %}
<script src="{% static 'institute/cards.js' %}"></script>
{% endblock script_links %}

institute/templates/institute/developers.html
{% extends 'institute/base_public_pages.html' %}

{% block title %}Dev Team{% endblock title %}

{% block style_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'institute/cards.css' %}">
{% endblock style_links %}


{% block content %}
<div class="container-fluid my-5 pt-5">
  <div class="text-center">
    <h2 class="d-inline border-bottom border-info">Development Team</h2>
  </div>
  <div class="row justify-content-aroud">
    <div class="col-md-4 mt-4">
      <h4 class="text-center mb-3">Faculty Advisor</h4>
      <div class="row jutify-content-center">
        <div class="col-12 d-flex jutify-content-center">
          <div class="card mx-auto mt-3" style="width: 18rem; max-width:100%;">
            <img class="card-img-top" src="{% static 'institute/srilatha.jpg' %}" alt="Block Image"
              style="width: auto; height: 250px;">
            <div class="card-body">
              <h5 class="card-title">Dr. Srilatha Chebrolu</h5>
              <div class="card-text">
                <p>Assisstant Professor</p>
              </div>
              <div class="card-reveal">
                <h4>Dr. Srilatha Chebrolu</h4>
                <span>Assistant Professor, Department of CSE</span>
                <h5 class="mt-4">Contact:</h5>
                <p>Phone: +91-8330967036</p>
                <p>eMail ID: <a href="mailto:srilatha.chebrolu@nitandhra.ac.in">srilatha.chebrolu@nitandhra.ac.in</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col mt-4">
      <h4 class="text-center mb-3">Student Developers</h4>
      <div class="row justify-content-aroud">
        <div class="col-md-6 px-3 d-flex justify-content-center">
          <div class="card mt-3" style="width: 18rem; max-width:100%;">
            <img class="card-img-top" src="{% static 'institute/eswar.jpg' %}" alt="Block Image"
              style="width: auto; height: 250px;">
            <div class="card-body">
              <h5 class="card-title">Eswar Prasad Clinton. A</h5>
              <div class="card-text">
                <p>Computer Science and Engineering</p>
              </div>
              <div class="card-reveal">
                <h4>Eswar Prasad Clinton. A</h4>
                <span>Computer Science and Engineering, Batch of 2018-22</span>
                <h5 class="mt-4">Contact:</h5>
                <p>eMail ID: <a href="mailto:411818@student.nitandhra.ac.in" class="card-link">411818@student.nitandhra.ac.in</a></p>
                <p>LinkedIn: <a href="https://www.linkedin.com/in/eswar-clynn" target="_blank" class="card-link">https://www.linkedin.com/in/eswar-clynn</a></p>
                <p>Phone: +91 80565 48745</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 px-3 d-flex justify-content-center">
          <div class="card mt-3" style="width: 18rem; max-width:100%;">
            <img class="card-img-top" src="{% static 'institute/chaithanya.jpg' %}" alt="Block Image"
              style="width: auto; height: 250px;">
            <div class="card-body">
              <h5 class="card-title">Ravuri Lalitha Krishna Chaithanya</h5>
              <div class="card-text">
                <p>Computer Science and Engineering</p>
              </div>
              <div class="card-reveal">
                <h4>Ravuri Lalitha Krishna Chaithanya</h4>
                <span>Computer Science and Engineering, Batch of 2018-22</span>
                <h5 class="mt-4">Contact:</h5>
                <p>eMail ID: <a href="mailto:411866@student.nitandhra.ac.in" class="card-link">411866@student.nitandhra.ac.in</a></p>
                <p>LinkedIn: <a href="https://www.linkedin.com/in/chaithanya-rlk-5b14a719b" target="_blank" class="card-link">https://www.linkedin.com/in/chaithanya-rlk-5b14a719b</a></p>
                <p>Phone: +91 88979 23566</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block script_links %}
<script src="{% static 'institute/cards.js' %}"></script>
{% endblock script_links %}

institute/templates/institute/grid-gallery.html
{% extends 'institute/base_public_pages.html' %}

{% block title %}Gallery{% endblock title %}


{% block style_links %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
<link rel="stylesheet" href="{% static 'institute/grid-gallery.css' %}">
{% endblock style_links %}


{% block content %}
<section class="gallery-block grid-gallery my-5 pt-5">
  <div class="container">
    <div class="heading">
      <h2 class="mb-4">NIT AP Hostels Gallery</h2>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img1.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img1.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img2.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img2.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img6.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img6.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img4.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img4.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img5.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img5.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img3.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img3.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img7.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img7.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href=".{% static 'institute/img10.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img10.jpg' %}">
        </a>
      </div>
      <div class="col-md-6 col-lg-4 item d-flex justify-content-center">
        <a class="lightbox" href="{% static 'institute/img9.jpg' %}">
          <img class="img-fluid image scale-on-hover" src="{% static 'institute/img9.jpg' %}">
        </a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

{% block script_links %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
<script>
  baguetteBox.run('.grid-gallery', { animation: 'slideIn' });
</script>
{% endblock script_links %}

institute/templates/institute/index.html
{% extends 'institute/base_public_pages.html' %}

{% block title %}Home{% endblock title %}

{% block style_links %}
{% load static %}
<link rel="stylesheet" href="{% static 'institute/index.css' %}">
{% endblock style_links %}


{% block content %}  
<div class="container main-container">
  <div class="row">
    <div class="col d-none d-md-flex align-items-center">
      <img src="{% static 'institute/bg.jpeg' %}" alt="Institute_Arch" class="img-thumbnail" style="width:inherit;">
    </div>
    <div class="col p-md-5">
      <h4 style="color: black; font-weight:800; margin-bottom: 1.3em;" class="text-center">NATIONAL INSTITUTE OF TECHNOLOGY, ANDHRA PRADESH<br> - HOSTEL MANAGEMENT SYSTEM</h4>
      <div class="row">
        <div class="col-6 text-center text-md-right">
          <a href="{% url 'django_auth:login'%}"><button class="link-item">Log In</button></a>
        </div>
        <div class="col text-center text-md-left">
          <a href="{% url 'django_auth:signup' %}"><button class="link-item">Sign Up</button></a>
        </div>
      </div>
      <div class="row mt-5 text-center">
        <div class="col-12">
          <a href="{% url 'institute:gallery' %}" class="small"><button class="link-item">Gallery - Take a look</button></a>
        </div>
        <div class="col-12 mt-2">
          <a href="{% url 'institute:hostels' %}" class="small"><button class="link-item">Blocks Informations</button></a>
        </div>
        <div class="col-12 mt-2">
          <a href="{% url 'institute:contact' %}" class="small"><button class="link-item">Contact Us!</button></a>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock content %}
  