complaints/urls.py
from django.urls import path
from . import views
from .models import MedicalIssue, Complaint
from .forms import ComplaintCreationForm, MedicalIssueUpdationForm, ComplaintUpdationForm

app_name= 'complaints'

urlpatterns = [
    path('complaint/new/', views.ComplaintCreateView.as_view(model = Complaint, form_class = ComplaintCreationForm), name='registerComplaint'),
    path('complaint/<int:pk>/', views.ComplaintDetailView.as_view(model = Complaint), name='complaint_detail'),
    path('complaint/<int:pk>/edit', views.ComplaintUpdateView.as_view(model = Complaint, form_class = ComplaintUpdationForm), name='complaint_edit'),
    path('complaint/<int:pk>/delete', views.ComplaintDeleteView.as_view(model = Complaint), name='complaint_delete'),
    path('medical/new/', views.ComplaintCreateView.as_view(model = MedicalIssue, fields = ['summary', 'detailed']), name='registerMedical'),
    path('medical/<int:pk>/', views.ComplaintDetailView.as_view(model = MedicalIssue), name='medicalissue_detail'),
    path('medical/<int:pk>/edit', views.ComplaintUpdateView.as_view(model = MedicalIssue, form_class = MedicalIssueUpdationForm), name='medicalissue_edit'),
    path('medical/<int:pk>/delete', views.ComplaintDeleteView.as_view(model = MedicalIssue), name='medicalissue_delete'),
]

django_auth/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name= 'django_auth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate-email/', ActivationEmailResendView.as_view(), name='send_activate_email'),
    path('activate/<uidb64>/<token>/', account_activate, name='account_activate'),
    path('activation-email-sent/', ActivationEmailSentView.as_view(), name='account_activation_sent'),
    path('change-password/', PasswordChangeView.as_view(), name='change_password'),
    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password-sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]

hosteldb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('institute.urls')),
    path('official/', include('officials.urls')),
    path('student/', include('students.urls')),
    path('', include('complaints.urls')),
    path('staff/', include('workers.urls')),
    
    path('auth/', include('django_auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

institute/urls.py
from django.urls import path

from . import views

app_name= 'institute'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery',views.gallery, name='gallery'),
    path('block-gallery/',views.hostels,name='hostels'),
    path('contact/',views.contact,name='contact'),
    path('developer-team/',views.developers, name='developers'),

]

officials/urls.py
from django.urls import path
from django.conf.urls.static import static 
from django.conf import settings
from . import views

app_name= 'officials'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('attendance/', views.attendance, name='attendance'),
    path('attendance-staff/', views.attendance_workers, name='attendance_workers'),
    path('attendance-log/', views.attendance_log, name='attendance_log'),
    path('generate-attendance-sheet/', views.generate_attendance_sheet, name='generate_attendance_sheet'),
    path('grant-outing/', views.grant_outing, name='grant_outing'),
    path('outing/<int:pk>', views.outing_detail, name='outing_detail'),
    path('block-layout/', views.blockSearch, name='blockSearch'),
    # path('search/',views.search, name='search'),

    path('student-list/', views.StudentListView.as_view(), name='student_list'),
    path('student/<int:pk>', views.StudentDetailView.as_view(), name='student_detail'),
    path('register-student/', views.StudentRegisterView.as_view(), name='register_student'),
    path('edit-student/<int:pk>', views.StudentUpdateView.as_view(), name='edit_student'),
    path('delete-student/<int:pk>', views.StudentDeleteView.as_view(), name='delete_student'),

    path('official-list/',views.OfficialListView.as_view(),name="emp_list"),
    path('register-official/', views.OfficialRegisterView.as_view(), name='register_official'),
    path('edit-official/<int:pk>', views.OfficialUpdateView.as_view(), name='edit_official'),
    path('delete-official/<int:pk>', views.OfficialDeleteView.as_view(), name='delete_official'),

    path('staff-list/',views.WorkerListView.as_view(),name="workers_list"),
    path('register-staff/', views.WorkerRegisterView.as_view(), name='register_worker'),
    path('edit-staff/<int:pk>', views.WorkerUpdateView.as_view(), name='edit_worker'),
    path('delete-staff/<int:pk>', views.WorkerDeleteView.as_view(), name='delete_worker'),

    path('complaint-list/', views.ComplaintListView.as_view(), name="complaint_list"),
    path('medical-issue-list/', views.MedicalIssueListView.as_view(), name="medical_issue_list")

    # path('water-cans/', views.watercan, name='watercan'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from . import views

app_name= 'students'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('outings', views.OutingListView.as_view(), name='outing_list'),
    path('outing/new', views.OutingCreateView.as_view(), name='outing_new'),
    path('outing/<int:pk>/edit', views.OutingUpdateView.as_view(), name='outing_edit'),
    path('attendance_history', views.attendance_history, name='attendance_history'),
]

workers/urls.py
from django.urls import path
from . import views

app_name= 'workers'

urlpatterns = [
    path('home/', views.home, name='home'),
]

officials/models.py
from django.db import models
# from institute.models import Block

# Create your models here.
# class WaterCan(models.Model):

#     date = models.DateField(null=False)
#     block = models.ForeignKey(Block,on_delete=models.CASCADE, null=False)
#     received = models.IntegerField(null=False)
#     given = models.IntegerField(null=False)

#     def __str__(self):
#         return str(self.block.block_id)+','+str(self.date)

officials/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.detail import DetailView
from institute.models import Block, Student, Official
from students.models import Attendance, RoomDetail, Outing
from django.contrib import messages
from django.http.response import Http404, HttpResponseForbidden
from complaints.models import Complaint
from workers.models import Worker, Attendance as AttendanceWorker

def official_check(user):
    return user.is_authenticated and user.is_official

def chief_warden_check(user):
    return official_check(user) and user.official.is_chief()


# Create your views here.
@user_passes_test(official_check)
def home(request):
    user = request.user
    official = user.official
    if official.is_chief():
        present_students = Attendance.objects.filter(status='Present')
        absent_students = Attendance.objects.filter(status='Absent')
        complaints = official.related_complaints()

    else:
        if not official.block: 
            raise Http404('You are currently not appointed any block! Please contact Admin')

        student_rooms = official.block.roomdetail_set.all()
        student_ids = student_rooms.values_list('student', flat=True)
        students = Student.objects.filter(pk__in=student_ids)
        present_students = Attendance.objects.filter(student__in=students, status='Present')
        absent_students = Attendance.objects.filter(student__in=students, status='Absent')
        complaints = official.related_complaints()

    return render(request, 'officials/home.html', {'user_details': official, 'present':present_students, 'absent':absent_students, 'complaints':complaints,})


@user_passes_test(official_check)
def profile(request):
    user = request.user
    official = user.official
    complaints = Complaint.objects.filter(user = user)
    return render(request, 'officials/profile.html', {'official': official, 'complaints': complaints})


@user_passes_test(official_check)
@csrf_exempt
def attendance(request):
    user = request.user
    official = user.official
    block = official.block
    attendance_list  = Attendance.objects.filter(student__in=block.roomdetail_set.all().values_list('student', flat=True))
    date = None

    if request.method == 'POST' and request.POST.get('submit'):
        date = request.POST.get('date')
        for attendance in attendance_list:
            if request.POST.get(str(attendance.id)): attendance.mark_attendance(date, request.POST.get(str(attendance.id)))

        messages.success(request, f'Attendance marked for date: {date}')

    if request.GET.get('for_date'):
        date = request.GET.get('for_date')
        messages.info(request, f'Selected date: {date}')
        for item in attendance_list:
            if item.present_dates and date in set(item.present_dates.split(',')): item.present_on_date = True
            if item.absent_dates and date in set(item.absent_dates.split(',')): item.absent_on_date = True

    return render(request, 'officials/attendance.html', {'official': official, 'attendance_list': attendance_list, 'date': date})


@user_passes_test(official_check)
@csrf_exempt
def attendance_workers(request):
    user = request.user
    official = user.official
    block = official.block
    attendance_list  = AttendanceWorker.objects.filter(worker__in=block.worker_set.all())
    date = None 

    if request.method == 'POST' and request.POST.get('submit'):
        date = request.POST.get('date')
        for attendance in attendance_list:
            if request.POST.get(str(attendance.id)): attendance.mark_attendance(date, request.POST.get(str(attendance.id)))

        messages.success(request, f'Staff Attendance marked for date: {date}')

    if request.GET.get('for_date'):
        date = request.GET.get('for_date')
        messages.info(request, f'Selected date: {date}')
        for item in attendance_list:
            if item.present_dates and  date in set(item.present_dates.split(',')): item.present_on_date = True
            if item.absent_dates and date in set(item.absent_dates.split(',')): item.absent_on_date = True

    return render(request, 'officials/attendance_workers.html', {'official': official, 'attendance_list': attendance_list, 'date': date})


@user_passes_test(official_check)
def attendance_log(request):
    user = request.user
    official = user.official
    student = None
    present_attendance = None
    absent_attendance = None
    present_dates = None
    absent_dates = None

    if official.is_chief():
        attendance_list = Attendance.objects.all()
    else:
        attendance_list = Attendance.objects.filter(student__in = official.block.roomdetail_set.all().values_list('student', flat=True))

    if request.GET.get('by_regd_no'):
        try:
            student = attendance_list.get(student__regd_no = request.GET.get('by_regd_no')).student
            if student.attendance.present_dates: present_dates = student.attendance.present_dates.split(',') 
            if student.attendance.absent_dates: absent_dates = student.attendance.absent_dates.split(',')
        except Attendance.DoesNotExist:
            messages.error(request, "Invalid Student Registration No.")

    if request.GET.get('by_date'):
        present_attendance = attendance_list.filter(present_dates__contains = request.GET.get('by_date'))
        absent_attendance = attendance_list.filter(absent_dates__contains = request.GET.get('by_date'))

        if present_attendance.count() == 0 and absent_attendance.count() == 0:
            messages.error(request, "No Attendance Records Found!")

    return render(request, 'officials/attendance_log.html', {'official':official, 'student': student, 'date': request.GET.get('by_date'),'present_attendance': present_attendance, 'absent_attendance': absent_attendance, 'present_dates': present_dates, 'absent_dates': absent_dates})


@user_passes_test(official_check)
def generate_attendance_sheet(request):
    from .utils import AttendanceBookGenerator
    from django.utils import timezone
    from django.http import HttpResponse
    
    year_month = request.GET.get("year_month")
    block_id = request.GET.get("block_id")

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',)
    response['Content-Disposition'] = 'attachment; filename=Attendance({date}).xlsx'.format(date=timezone.now().strftime('%d-%m-%Y'),)
    
    BookGenerator = AttendanceBookGenerator(block_id, year_month)
    workbook = BookGenerator.generate_workbook()
    workbook.save(response)

    return response

@user_passes_test(official_check)
def grant_outing(request):
    user = request.user
    official = user.official
    outings = Outing.objects.filter(student__in=official.block.roomdetail_set.all().values_list('student', flat=True), permission="Pending")

    return render(request, 'officials/grant_outing.html', {'official': official, 'outings': outings})


@user_passes_test(official_check)
def outing_detail(request, pk):
    outing = get_object_or_404(Outing, id=pk)

    if request.POST.get('permission'):
        outing.permission = request.POST.get('permission')
        outing.save()

        messages.success(request, f'Outing successfully {outing.permission.lower()} to {outing.student.name}')
        return redirect('officials:grant_outing')
    return render(request, 'officials/outing_show.html', {'outing': outing})


@user_passes_test(chief_warden_check)
@csrf_exempt
def blockSearch(request):
    user = request.user
    official = user.official
    blocks = Block.objects.all()

    if request.POST:
        block_id = request.GET.get('block')
        if request.POST.get('Add'):
            block = Block.objects.get(id = request.POST.get('block_id'))
            try:
                student = Student.objects.get(regd_no = request.POST.get('regd_no'))
                if not student.is_hosteller:
                    raise ValidationError("Cannot assign room to day scholars.")
                room_detail = student.roomdetail
                if room_detail.block and room_detail.room():
                    messages.error(request, f'Student {student.regd_no} already alloted room in {room_detail.block.name} {room_detail.room()}!')
                else:
                    room_detail.block = block
                    room_detail.floor = request.POST.get('floor')
                    room_detail.room_no = request.POST.get('room_no')
                    room_detail.full_clean()
                    room_detail.save()
                    messages.success(request, f'Student {student.regd_no} successfully alloted room in {room_detail.block.name} {room_detail.room()}!')
            except RoomDetail.DoesNotExist as error:
                # Day Scholars have no room detail.
                messages.error(request, "Cannot assign room to day scholars.")
            except ValidationError as error:
                for message in error.messages:
                    messages.error(request, message)
            except Student.DoesNotExist:
                messages.error(request, f'Student not found!')

        if request.POST.get('remove'):
            room_detail = RoomDetail.objects.get(id = request.POST.get('roomdetail_id'))
            room_detail.block = None
            room_detail.floor = None
            room_detail.room_no = None
            room_detail.save()
            messages.success(request, f'Student {room_detail.student.regd_no} removed from room.')

        return redirect(reverse_lazy('officials:blockSearch') + '?block={}'.format(block_id))

    if request.GET.get('block'):
        from django.core.serializers import serialize
        block = Block.objects.get(id=request.GET.get('block'))
        block_json = serialize('json', [block])

officials/templates/officials/base_officials.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}{% endblock %} - Hostel Management System </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css" integrity="sha512-O03ntXoVqaGUTAeAmvQ2YSzkCvclZEcPQu1eqloPaHfJ5RuNGiS4l+3duaidD801P50J28EHyonCV06CUlTSag==" crossorigin="anonymous" />
  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,500&display=swap"
    rel="stylesheet">
  {% load static %}
  <link href="{% static 'officials/application.css' %}" rel="stylesheet">
  {% block style_links %}{% endblock style_links %}
    
</head>

<body>
  <nav class="navbar row fixed-top px-4" id="topnav">
    <div class="col-12 p-0 d-flex justify-content-between align-items-center">
      <div class="">
        <span style="cursor: pointer;" onclick="openNav()"><span class="fa fa-bars nav-icon"></span></span>
      </div>
  
      <div class="d-flex justify-content-center">
        <span class="d-none d-md-block nav-title"><img src="{% static 'officials/logo_small.png' %}" alt="Institute Logo" class="mr-3">NIT Andhra Pradesh - Hostel Management System</span>
        <span class="d-block d-md-none nav-title"><img src="{% static 'officials/logo_small.png' %}" alt="Institute Logo" class="mr-2">NIT AP - Hostels</span>
      </div>
  
      <div class="">
        
        {% if request.user.is_official %}
        <a href="{% url 'officials:profile' %}"><i class="fa fa-user-circle-o nav-icon"></i></a>
        {% endif %}
        {% if request.user.is_student %}
        <a href="{% url 'students:home' %}"><i class="fa fa-user-circle-o nav-icon"></i></a>
        {% endif %}
        {% if request.user.is_worker %}
        <a href="{% url 'workers:home' %}"><i class="fa fa-user-circle-o nav-icon"></i></a>
        {% endif %}
          
      </div>
    </div>
  </nav>


  <div id="mySidenav" class="sidenav">
    <a style="cursor: pointer;" class="closebtn" onclick="closeNav()">&times;</a>
    {% with url_name=request.resolver_match.url_name %}
    
    {% if request.user.is_official and request.user.official.is_chief %}
      <a href="{% url 'officials:home' %}" class="{% if url_name == 'home' %}active{% endif %}"><span class="mr-3"><i class="fa fa-tachometer"></i></span>Dashboard</a>
      <a href="{% url 'officials:blockSearch' %}" class="{% if url_name == 'blockSearch' %}active{% endif %}"><span class="mr-3"><i class="fa fa-building"></i></span> Block Layout</a>
      <a href="{% url 'officials:attendance_log' %}" class="{% if url_name == 'attendance_log' %}active{% endif %}"><span class="mr-3"><i class="fa fa-calendar"></i></span> Attendance Log</a>
      <a href="{% url 'officials:student_list' %}" class="{% if url_name == 'student_list' %}active{% endif %}"><span class="mr-3"><i class="fa fa-graduation-cap"></i></span> Student List</a>
      <a href="{% url 'officials:emp_list' %}" class="{% if url_name == 'emp_list' %}active{% endif %}"><span class="mr-3"><i class="fa fa-users"></i></span>Official List</a>
      <a href="{% url 'officials:workers_list' %}"  class="{% if url_name == 'workers_list' %}active{% endif %}"><span class="mr-3"><i class="fa fa-file-text"></i></span>Staff List</a>      
      <a href="{% url 'officials:complaint_list' %}"  class="{% if url_name == 'complaint_list' %}active{% endif %}"><span class="mr-3"><i class="fa fa-quote-right"></i></span>Complaints List</a>      
      <a href="{% url 'officials:medical_issue_list' %}"  class="{% if url_name == 'medical_issue_list' %}active{% endif %}"><span class="mr-3"><i class="fa fa-ambulance"></i></span>Medical Issues List</a>      
    
    {% endif %}
    {% if request.user.is_official and not request.user.official.is_chief %}
      <a href="{% url 'officials:home' %}" class="{% if url_name == 'home' %}active{% endif %}"><span class="mr-3"><i class="fa fa-tachometer"></i></span>Dashboard</a>
      <a href="{% url 'officials:attendance' %}" class="{% if url_name == 'attendance' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-list"></i></span> Attendance</a>
      <a href="{% url 'officials:attendance_workers' %}" class="{% if url_name == 'attendance_workers' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-users"></i></span> Attendance-Staff</a>
      <a href="{% url 'officials:attendance_log' %}" class="{% if url_name == 'attendance_log' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-calendar"></i></span> Attendance Log</a>
      <a href="{% url 'officials:student_list' %}" class="{% if url_name == 'student_list' %}active{% endif %}"><span class="mr-3"><i class="fa fa-graduation-cap"></i></span> Student List</a>
      <a href="{% url 'officials:grant_outing' %}" class="{% if url_name == 'grant_outing' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-map-marker" ></i></span> Outing Requests</a>
      <a href="{% url 'officials:complaint_list' %}"  class="{% if url_name == 'complaint_list' %}active{% endif %}"><span class="mr-3"><i class="fa fa-quote-right"></i></span>Complaints List</a>      
    
    {% endif %}
    {% if request.user.is_student %}
      <a href="{% url 'students:home' %}" class="{% if url_name == 'home' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-tachometer"></i></span> Dashboard</a>
      <a href="{% url 'students:outing_new' %}" class="{% if url_name == 'outing_new' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-map-marker"></i></span> Outing Application</a>
      <a href="{% url 'students:attendance_history' %}" class="{% if url_name == 'attendance_history' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-list" ></i></span> Attendance History</a>
      <a href="{% url 'students:outing_list' %}" class="{% if url_name == 'outing_list' %}active{% endif %}"><span span class="mr-3"><i class="fa fa-history" ></i></span> Outing History</a>
    {% endif %}

    <a href="{% url 'complaints:registerMedical' %}"><span class="mr-3"><i class="fa fa-medkit"></i></span> Medical Issue</a>
    <a href="{% url 'complaints:registerComplaint' %}"><span class="mr-3"><i class="fa fa-commenting"></i></span>Register Complaint</a>
    <a href="{% url 'django_auth:logout' %}"><span class="mr-3"><i class="fa fa-sign-out"></i></span>Log Out</a>
  </div>
  {% endwith %}
  
  <div class="container main-container">
    {% block content %}
    {% endblock content %}
  </div>

  <script>
    var toast_messages = [];
    {% if messages %}
      {% for message in messages %}
        toast_messages.push({
          tag: '{{ message.tags }}',
          message: '{{ message }}'
        })
      {% endfor %}
    {% endif %}
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/js/iziToast.min.js" integrity="sha512-Zq9o+E00xhhR/7vJ49mxFNJ0KQw1E1TMWkPTxrWcnpfEFDEXgUiwJHIKit93EW/XxE31HSI5GEOW06G6BF1AtA==" crossorigin="anonymous"></script>
  {% block script_links %}{% endblock script_links %}
  <script src="{% static 'officials/application.js' %}"></script>

</body>
</html>

officials/templates/officials/grant_outing.html
{% extends 'officials/base_officials.html' %}

{% block title %}Outing Requests{% endblock title %}

{% block content %}

<h1 class="text-center">Outing Requests</h1>
<hr>
<div class="overflow-auto p-4">
  <table class="table table-hover table-muted table-striped">
    <thead>
      <tr>
        <th>Regd No.</th>
        <th>Student Name</th>
        <th>Year</th>
        <th>Branch</th>
        <th>Phone</th>
        <th>From</th>
        <th>To</th>
        <th>Allow?</th>
      </tr>
    </thead>

    <tbody>

      {% for outing in outings %}
      <tr data-row-href="{% url 'officials:outing_detail' outing.id %}">
        <td>{{outing.student.regd_no}}</td>
        <td>{{outing.student.name}}</td>
        <td>{{outing.student.year}}</td>
        <td>{{outing.student.branch}}</td>
        <td>{{outing.student.phone}}</td>
        <td>{{outing.fromDate|date:'d-m-Y' }}</td>
        <td>{{outing.toDate|date:'d-m-Y' }}</td>
        <td nowrap>
          <form action="{% url 'officials:outing_detail' outing.id %}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to grant outing to {{outing.student.name}}?');">{% csrf_token %}
            <input type="hidden" name="permission" value="Granted" />
            <button type="submit" class="btn btn-success ml-3">Grant</button>
          </form>
          <form action="{% url 'officials:outing_detail' outing.id %}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to reject?');">{% csrf_token %}
            <input type="hidden" name="permission" value="Rejected" />
            <button type="submit" class="btn btn-danger ml-3">Reject</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="text-center"><small>Click on a row to view student details and outing history!</small></div>
{% endblock content %}


{% block script_links %}
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
  $(document).ready(function () {
    $('table').DataTable({
      "lengthMenu": [[10, 25, 50, 100, 250, 500, 1000, -1], [10, 25, 50, 100, 250, 500, 1000, "All"]],
      "info": false,
      "dom": '<"row"<"col-3"l><"col"f><"col"p>>t'
    });
  });
</script>
{% endblock script_links %}

officials/templates/officials/official_list.html
{% extends 'officials/base_officials.html' %}

{% block title %}Officials List{% endblock title %}

{% block content %}

<div class="text-center">
  <h1 class="text-center">Officials List</h1>
  <a href="{% url 'officials:register_official' %}" class="btn btn-primary">+ Add Official</a>
</div>
<hr>
<div class="overflow-auto p-4">
  <table class="table table-hover table-muted table-striped" id="att-table">
    <thead>
      <tr>
        <th>Employee ID</th>
        <th>Name</th>
        <th>Designation</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Block</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for stud in object_list %}
      <tr>
        <td>{{stud.emp_id}}</td>
        <td>{{stud.name}}</td>
        <td>{{stud.designation}}</td>
        <td>{{stud.account_email}}</td>
        <td>{{stud.phone}}</td>
        <td>{{stud.block.short_name}}</td>
        <td nowrap>
          <a href="{% url 'officials:edit_official' stud.id %}" target="_blank" class="btn btn-primary">Edit</a>
          <form action="{% url 'officials:delete_official' stud.id %}" method="POST" class="d-inline"
            onsubmit="return confirm('Are you sure you want to delete {{stud.name}}?');">{% csrf_token %}
            <input type="submit" class="btn btn-danger ml-3" value="Delete" />
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock content %}


{% block script_links %}
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
  $(document).ready(function () {
    $('table').DataTable({
      "lengthMenu": [[10, 25, 50, 100, 250, 500, 1000, -1], [10, 25, 50, 100, 250, 500, 1000, "All"]],
      "info": false,
      "dom": '<"row"<"col-3"l><"col"f><"col"p>>t'
    });
  });
</script>
{% endblock script_links %}